# config.py

# AWS credentials
AWS_ACCESS_KEY_ID = 'YOUR_ACCESS_KEY_ID'
AWS_SECRET_ACCESS_KEY = 'YOUR_SECRET_ACCESS_KEY'
AWS_REGION = 'us-east-1'

# AWS S3 bucket names
AWS_S3_INPUT_BUCKET = 'YOUR_INPUT_BUCKET_NAME'
AWS_S3_OUTPUT_BUCKET = 'YOUR_OUTPUT_BUCKET_NAME'
